f = open("uMult_times.txt", "w")
f.close()
f = open("wMult_times.txt", "w")
f.close()
f = open("wMultU1_times.txt", "w")
f.close()
f = open("wMultU2_times.txt", "w")
f.close()
f = open("wMultU3_times.txt", "w")
f.close()